//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file to NLock.
        /// </summary>
        public static string AddToNLock {
            get {
                return ResourceManager.GetString("AddToNLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred
        ///.
        /// </summary>
        public static string An_error_occurred {
            get {
                return ResourceManager.GetString("An_error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want create the folder...
        /// </summary>
        public static string AsktoCreateFolder {
            get {
                return ResourceManager.GetString("AsktoCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want overwrite the file...
        /// </summary>
        public static string AsktoOverwrite {
            get {
                return ResourceManager.GetString("AsktoOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed... 
        ///Bad image captured.
        /// </summary>
        public static string BadFaceCaptured {
            get {
                return ResourceManager.GetString("BadFaceCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera detected...
        ///Please continue.
        /// </summary>
        public static string CameraDetected {
            get {
                return ResourceManager.GetString("CameraDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CameraDetectedContinue {
            get {
                object obj = ResourceManager.GetObject("CameraDetectedContinue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect the camera..
        ///Please connect a camera..
        /// </summary>
        public static string CameraNotDetected {
            get {
                return ResourceManager.GetString("CameraNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel password retry.
        /// </summary>
        public static string Cancel_password_retry {
            get {
                return ResourceManager.GetString("Cancel_password_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled....
        /// </summary>
        public static string Canceled___ {
            get {
                return ResourceManager.GetString("Canceled___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture failed..
        ///Please look at the camera... .
        /// </summary>
        public static string CaptureFailed {
            get {
                return ResourceManager.GetString("CaptureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing user....
        /// </summary>
        public static string Capturing_user___ {
            get {
                return ResourceManager.GetString("Capturing_user___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neurotechnology.
        /// </summary>
        public static string CompanyNeurotechnology {
            get {
                return ResourceManager.GetString("CompanyNeurotechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2015-2016.
        /// </summary>
        public static string CopyrightYear {
            get {
                return ResourceManager.GetString("CopyrightYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device manager not responding..!.
        /// </summary>
        public static string Device_manager_not_responding___ {
            get {
                return ResourceManager.GetString("Device_manager_not_responding___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found...
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed... 
        ///No files added. Empty container.
        /// </summary>
        public static string EmptyContainer {
            get {
                return ResourceManager.GetString("EmptyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filed added, folder is empty....
        /// </summary>
        public static string EmptyFolderNoFilesAdded {
            get {
                return ResourceManager.GetString("EmptyFolderNoFilesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty password.
        /// </summary>
        public static string EmptyPasswd {
            get {
                return ResourceManager.GetString("EmptyPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon err {
            get {
                object obj = ResourceManager.GetObject("err", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit ?.
        /// </summary>
        public static string ExitQ {
            get {
                return ResourceManager.GetString("ExitQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction is.
        /// </summary>
        public static string Extraction_is {
            get {
                return ResourceManager.GetString("Extraction_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap F12_HelpErrorBoxGrey {
            get {
                object obj = ResourceManager.GetObject("F12_HelpErrorBoxGrey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed !.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed....
        /// </summary>
        public static string Failed___ {
            get {
                return ResourceManager.GetString("Failed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check components activation status. Error message:.
        /// </summary>
        public static string Failed_to_check__ {
            get {
                return ResourceManager.GetString("Failed_to_check__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract files to : .
        /// </summary>
        public static string FailedExtractTo {
            get {
                return ResourceManager.GetString("FailedExtractTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is changed.
        /// </summary>
        public static string File_is_changed {
            get {
                return ResourceManager.GetString("File_is_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is corrupted or not a valid NLock file : .
        /// </summary>
        public static string FileCorrupted {
            get {
                return ResourceManager.GetString("FileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Already Exists.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File opening failed.
        /// </summary>
        public static string FileOpeningFailed {
            get {
                return ResourceManager.GetString("FileOpeningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command, please contact System Administrator.
        /// </summary>
        public static string Invalid_command {
            get {
                return ResourceManager.GetString("Invalid_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password....
        /// </summary>
        public static string Invalid_password___ {
            get {
                return ResourceManager.GetString("Invalid_password___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File !.
        /// </summary>
        public static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User !.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses obtained.
        /// </summary>
        public static string Licenses_obtained {
            get {
                return ResourceManager.GetString("Licenses_obtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Lock_64x {
            get {
                object obj = ResourceManager.GetObject("Lock_64x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock file....
        /// </summary>
        public static string Lock_file___ {
            get {
                return ResourceManager.GetString("Lock_file___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking.
        /// </summary>
        public static string Locking {
            get {
                return ResourceManager.GetString("Locking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking....
        /// </summary>
        public static string Locking___ {
            get {
                return ResourceManager.GetString("Locking___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking Canceled....
        /// </summary>
        public static string Locking_Canceled___ {
            get {
                return ResourceManager.GetString("Locking_Canceled___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking Successful....
        /// </summary>
        public static string Locking_Successful___ {
            get {
                return ResourceManager.GetString("Locking_Successful___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one face detected.. Restarting capturing..
        /// </summary>
        public static string ManyFaces {
            get {
                return ResourceManager.GetString("ManyFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLock.
        /// </summary>
        public static string NLock {
            get {
                return ResourceManager.GetString("NLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .nlk.
        /// </summary>
        public static string NLock_Extention {
            get {
                return ResourceManager.GetString("NLock_Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLock is using .
        /// </summary>
        public static string NLock_is_using {
            get {
                return ResourceManager.GetString("NLock_is_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLock Unlocker .
        /// </summary>
        public static string NLock_Unlocker_ {
            get {
                return ResourceManager.GetString("NLock_Unlocker_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NoCameraDetected {
            get {
                object obj = ResourceManager.GetObject("NoCameraDetected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid NLock File : .
        /// </summary>
        public static string Not_a_valid_NLock_File___ {
            get {
                return ResourceManager.GetString("Not_a_valid_NLock_File___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required licenses obtained.
        /// </summary>
        public static string Not_all_required_licenses_obtained {
            get {
                return ResourceManager.GetString("Not_all_required_licenses_obtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory.
        /// </summary>
        public static string Not_enough_memory {
            get {
                return ResourceManager.GetString("Not_enough_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening....
        /// </summary>
        public static string Opening___ {
            get {
                return ResourceManager.GetString("Opening___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file !.
        /// </summary>
        public static string OpeningFile {
            get {
                return ResourceManager.GetString("OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        public static string Out_of_memory {
            get {
                return ResourceManager.GetString("Out_of_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswdNotMatch {
            get {
                return ResourceManager.GetString("PasswdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not support password unlocking.
        /// </summary>
        public static string Password_not_supported {
            get {
                return ResourceManager.GetString("Password_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both passwords match.
        /// </summary>
        public static string PasswordsMatch {
            get {
                return ResourceManager.GetString("PasswordsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path - Given path is a folder name.
        /// </summary>
        public static string PathIsAFolder {
            get {
                return ResourceManager.GetString("PathIsAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press cancel to stop capturing....
        /// </summary>
        public static string Press_cancel_to_stop_capturing___ {
            get {
                return ResourceManager.GetString("Press_cancel_to_stop_capturing___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Question_32xLG {
            get {
                object obj = ResourceManager.GetObject("Question_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting capture process....
        /// </summary>
        public static string RestartCapture {
            get {
                return ResourceManager.GetString("RestartCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry using password.
        /// </summary>
        public static string Retry_using_password {
            get {
                return ResourceManager.GetString("Retry_using_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK....
        /// </summary>
        public static string SaveMsg {
            get {
                return ResourceManager.GetString("SaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings_32xMD {
            get {
                object obj = ResourceManager.GetObject("Settings_32xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StartImage {
            get {
                object obj = ResourceManager.GetObject("StartImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing....
        /// </summary>
        public static string StartMsg {
            get {
                return ResourceManager.GetString("StartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully extracted files to : .
        /// </summary>
        public static string SuccessExtractedTo {
            get {
                return ResourceManager.GetString("SuccessExtractedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful....
        /// </summary>
        public static string Successful___ {
            get {
                return ResourceManager.GetString("Successful___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully locked files to : .
        /// </summary>
        public static string SuccessfullyLockedFilesTo {
            get {
                return ResourceManager.GetString("SuccessfullyLockedFilesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.. User identified...!.
        /// </summary>
        public static string UnlockedUserIdentified {
            get {
                return ResourceManager.GetString("UnlockedUserIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocking.
        /// </summary>
        public static string Unlocking {
            get {
                return ResourceManager.GetString("Unlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocking....
        /// </summary>
        public static string Unlocking___ {
            get {
                return ResourceManager.GetString("Unlocking___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocking failed !.
        /// </summary>
        public static string UnlockingFailed {
            get {
                return ResourceManager.GetString("UnlockingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocking failed..
        ///Press Retry to retry unlocking....
        /// </summary>
        public static string UnlockingFailed_PressRetry {
            get {
                return ResourceManager.GetString("UnlockingFailed_PressRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verification failed....
        /// </summary>
        public static string User_verification_failed___ {
            get {
                return ResourceManager.GetString("User_verification_failed___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is valid Press OK....
        /// </summary>
        public static string ValidPath {
            get {
                return ResourceManager.GetString("ValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying user....
        /// </summary>
        public static string Verifying_user___ {
            get {
                return ResourceManager.GetString("Verifying_user___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying using password ....
        /// </summary>
        public static string Verifying_using_password____ {
            get {
                return ResourceManager.GetString("Verifying_using_password____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriLook SDK.
        /// </summary>
        public static string VeriLookSDK {
            get {
                return ResourceManager.GetString("VeriLookSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit NLock
        ///Exit ?.
        /// </summary>
        public static string WantToExitNLock {
            get {
                return ResourceManager.GetString("WantToExitNLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental feature..
        ///Duplicate file names are automatically renamed.
        /// </summary>
        public static string Warnning {
            get {
                return ResourceManager.GetString("Warnning", resourceCulture);
            }
        }
    }
}
